# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='code',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='language',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='style',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='title',
        ),
        migrations.AddField(
            model_name='snippet',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snippet',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='created',
            field=models.DateField(),
        ),
    ]
