# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20160227_0704'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Analysis',
        ),
    ]
