# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20160227_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
