# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20160304_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='days',
        ),
        migrations.AddField(
            model_name='analysis',
            name='attendance',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
